# Generated by Django 5.0.3 on 2024-04-03 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_clientpayment_payment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinstallment',
            name='client',
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateTimeField(auto_now_add=True)),
                ('paid_date', models.DateTimeField(auto_now=True)),
                ('paid_status', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('staff_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.staff')),
            ],
        ),
        migrations.DeleteModel(
            name='ClientPayment',
        ),
        migrations.DeleteModel(
            name='PaymentInstallment',
        ),
    ]
