# Generated by Django 5.0.3 on 2024-04-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='RowMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
            ],
        ),
    ]
