# Generated by Django 5.0.3 on 2024-04-02 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_clientpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpayment',
            name='installment_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.paymentinstallment'),
        ),
    ]
