# Generated by Django 5.0.3 on 2024-04-02 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_clientpayment_installment_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientpayment',
            old_name='installment_number',
            new_name='pay_installment_number',
        ),
    ]
