# Generated by Django 5.0.3 on 2024-04-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_installment_number_clientpayment_pay_installment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpayment',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clientpayment',
            name='payment_last_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clientpayment',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
