# Generated by Django 5.0.3 on 2024-04-03 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_paymentinstallment_client_bill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_one', models.CharField(max_length=100)),
                ('installment_two', models.CharField(max_length=100)),
                ('installment_three', models.CharField(max_length=100)),
                ('installment_four', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='bill',
            name='installment_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.installment'),
        ),
    ]
